### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by HugoChateauLaurent** [HugoChateauLaurent/remi-cpp#6]
- [ ] Implement high-pass filter (5Hz) to cancel DC offset
- [ ] Add noise in update
- [ ] Set seed
- [ ] Change number of neurons
